### ISSUE TITLE
Fonts for OSD not found (Pi)

### ISSUE THREAD

**Issue by Prutsium** [FormerLurker/Octolapse#628]
Octoprint version: 1.4.2
Octopi version: 0.18
Octolapse version: v0.4.1+u.88aa71f
Python version: 3.7.3

I made recently a fresh install of OctoPi and noticed some issues with fonts as Octolapse dont see any fonts anymore.
Font-Config is installed and fc-list give this result:
pi@octopi:/ $ fc-list
/usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf: DejaVu Serif:style=Bold
/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf: DejaVu Sans Mono:style=Book
/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf: DejaVu Sans:style=Book
/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf: DejaVu Sans:style=Bold
/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf: DejaVu Sans Mono:style=Bold
/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf: DejaVu Serif:style=Book

The log of Octolapse reports an error for a font but i cant select or deselect any font:
2020-11-21 15:33:28,677 - octolapse.render - ERROR - An error occurred while opening the selected font
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octolapse/render.py", line 115, in preview_overlay
    font = ImageFont.truetype(rendering_profile.overlay_font_path, size=50)
  File "/home/pi/oprint/lib/python3.7/site-packages/PIL/ImageFont.py", line 836, in truetype
    return freetype(font)
  File "/home/pi/oprint/lib/python3.7/site-packages/PIL/ImageFont.py", line 833, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/home/pi/oprint/lib/python3.7/site-packages/PIL/ImageFont.py", line 194, in __init__
    font, size, index, encoding, layout_engine=layout_engine
OSError: cannot open resource
2020-11-21 15:33:55,868 - octolapse.render - ERROR - An error occurred while opening the selected font
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octolapse/render.py", line 115, in preview_overlay
    font = ImageFont.truetype(rendering_profile.overlay_font_path, size=50)
  File "/home/pi/oprint/lib/python3.7/site-packages/PIL/ImageFont.py", line 836, in truetype
    return freetype(font)
  File "/home/pi/oprint/lib/python3.7/site-packages/PIL/ImageFont.py", line 833, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/home/pi/oprint/lib/python3.7/site-packages/PIL/ImageFont.py", line 194, in __init__
    font, size, index, encoding, layout_engine=layout_engine
OSError: cannot open resource
2020-11-21 15:34:17,048 - octolapse.render - ERROR - An error occurred while opening the selected font
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octolapse/render.py", line 115, in preview_overlay
    font = ImageFont.truetype(rendering_profile.overlay_font_path, size=50)
  File "/home/pi/oprint/lib/python3.7/site-packages/PIL/ImageFont.py", line 836, in truetype
    return freetype(font)
  File "/home/pi/oprint/lib/python3.7/site-packages/PIL/ImageFont.py", line 833, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/home/pi/oprint/lib/python3.7/site-packages/PIL/ImageFont.py", line 194, in __init__
    font, size, index, encoding, layout_engine=layout_engine
OSError: cannot open resource
2020-11-21 15:55:42,957 - octolapse.render - ERROR - An error occurred while opening the selected font
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octolapse/render.py", line 115, in preview_overlay
    font = ImageFont.truetype(rendering_profile.overlay_font_path, size=50)
  File "/home/pi/oprint/lib/python3.7/site-packages/PIL/ImageFont.py", line 836, in truetype
    return freetype(font)
  File "/home/pi/oprint/lib/python3.7/site-packages/PIL/ImageFont.py", line 833, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/home/pi/oprint/lib/python3.7/site-packages/PIL/ImageFont.py", line 194, in __init__
    font, size, index, encoding, layout_engine=layout_engine
OSError: cannot open resource

How could i fix this?

**Comment by FormerLurker** [comment]
Try installing from this URL in the plugin manager:  ```https://github.com/FormerLurker/Octolapse/archive/devel.zip```

Also, what version of python are you running?  I need to test this in both versions (2.7 and 3+)

**Comment by Prutsium** [comment]
As usual printer is running now but will do when it finishes.

Python version: 3.7.3

**Comment by FormerLurker** [comment]
Sounds good.  And use this url instead:  ```https://github.com/FormerLurker/Octolapse/archive/5a4b744dbf6105d426c35eb449076c9c101e9dc2.zip```

It's safer since I may be pushing more to devel.

**Comment by Prutsium** [comment]
Yeah seems to fix it :)
![image](https://user-images.githubusercontent.com/42968695/99888344-6810cc00-2c4c-11eb-80ab-476f9e3e5a8e.png)

Thanks for the quick reaction and solution.

**Comment by FormerLurker** [comment]
Awesome!  If you have a python 2.7 instance, I'd love to see if it works there too.  I will eventually get around to it :)

**Comment by Prutsium** [comment]
Pitty enough my both systems are Python 3 already :)

**Comment by FormerLurker** [comment]
Tested in python 2.7, and is working!  Closed :)
