### ISSUE TITLE
Canon R5 New file is in location /capt0000.jpg on the camera

### ISSUE THREAD

**Issue by fiveorders** [FormerLurker/Octolapse#749]
#### If this is a feature request describe it here

___REPLACE_THIS__FEATURE_REQUEST_DESCRIPTION_GOES_HERE

#### Version of Octolapse
 
Octolapse Version: Octolapse 0.4.1   Settings 4.0

#### Version of OctoPrint

OctoPrint Version: 1.6.1

#### When you ran into the problem, did you have diagnostic logging enabled?

Diagnostic Logging was Enabled: NO

#### What were you doing when the problem occurred

1. Testing 1. step `gphoto2 --auto-detect --capture-image`

#### What should have happened?
An image should be captured on the SD Card

#### What happened instead?
I hear the sound of camera taking a picture but there is No-Image on the SD card

#### Operating System running OctoPrint and Octolapse

OS Name: Raspberry Pi 3 
Os Version: Octoprint 1.6.1 Octolapse 0.4.1

#### Printer model & used firmware incl. version

Printer Model: ___REPLACE_THIS__PRINTER_MODEL_GOES_HERE
Printer Firmware Version: ___REPLACE_THIS__PRINTER_FIRMWARE_VERSION_GOES_HERE

#### Browser and version of browser, operating system running browser

Browser: ___REPLACE_THIS__BROWSER_VERSION_GOES_HERE
Browser OS: ___REPLACE_THIS__BROWSER_OS_GOES_HERE

#### Link to the gcode file you were printing when the problem occurred

Link to Gcode File: ___REPLACE_THIS__GCODE_FILE_LINK_GOES_HERE

#### Link to settings.json

Link to settings.json with all passwords removed: ___REPLACE_THIS__SETTINGS_JSON_LINK_GOES_HERE

#### Link to plugin_octolapse.log

Link to plugin_octolapse.log:  LINK_GOES_HERE

#### Link to octoprint.log

Link to octoprint.log:  ___REPLACE_THIS__LINK_GOES_HERE

#### Link to contents of Javascript console in the browser

Link to javascript console output: ___REPLACE_THIS__LINK_GOES_HERE

#### Screenshots and/or videos of the problem:

Screenshot/Video Links: ___REPLACE_THIS__LINKs_GO_HERE

## Please consider becoming a patron
If you like this project, [please support my work by becoming a patron,](https://www.patreon.com/bePatron?u=9588101) and consider adding a 'star' to the repository.  It takes a lot of time and effort to maintain the project and respond to issues.  The cost of test prints, software, cameras, printer parts, etc. can quickly add up, so every bit helps.

You can find various [videos and tutorials](https://www.youtube.com/channel/UCnnTLQetNw7FqfQOLJCMqoQ) by subscribing to my Youtube channel.  You can also [follow me on Twitter](https://twitter.com/FormerLurker1).

**Comment by fiveorders** [comment]
```
2021-06-26 16:02:19,639 - octolapse.__init__ - INFO - Started logging to file.
2021-06-26 16:02:19,848 - octolapse.settings - INFO - Creating settings from iterable.
2021-06-26 16:02:19,924 - octolapse.settings - INFO - Settings created from iterable.
2021-06-26 16:02:19,960 - octolapse.settings - INFO - Default settings loaded.
2021-06-26 16:01:32,431 - octolapse.__init__ - INFO - Started logging to file.
2021-06-26 16:01:32,462 - octolapse.settings - INFO - Loading existing settings file from: /home/pi/.octoprint/data/octolapse/settings.json.
2021-06-26 16:01:32,607 - octolapse.settings - INFO - Creating settings from iterable.
2021-06-26 16:01:33,032 - octolapse.settings - INFO - Settings created from iterable.
2021-06-26 16:01:33,078 - octolapse.settings - INFO - Settings file loaded.
2021-06-27 11:25:53,960 - octolapse.script - ERROR - An error occurred while executing 'DSLR - Snapshot Camera Script'
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octolapse/script.py", line 248, in execute_process
    self.proc = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/home/pi/scripts/take-snapshot.sh'
2021-06-27 11:29:40,616 - octolapse.script - ERROR - An error occurred while executing 'DSLR - Snapshot Camera Script'
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octolapse/script.py", line 248, in execute_process
    self.proc = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/home/pi/scripts/take-snapshot.sh'
2021-06-27 11:31:32,385 - octolapse.script - ERROR - Error output (stderr) for 'DSLR - Snapshot Camera Script':
	ERROR: Could not get image.
2021-06-27 11:33:11,294 - octolapse.script - ERROR - Error output (stderr) for 'DSLR - Snapshot Camera Script':
	ERROR: Could not get image.
2021-06-27 11:35:08,175 - octolapse.script - ERROR - Error output (stderr) for 'DSLR - Snapshot Camera Script':
	ERROR: Could not get image.
2021-06-27 11:35:32,831 - octolapse.script - ERROR - Error output (stderr) for 'DSLR - Snapshot Camera Script':
	ERROR: Could not get image.
2021-06-27 11:36:10,302 - octolapse.script - ERROR - Error output (stderr) for 'DSLR - Snapshot Camera Script':
	ERROR: Could not get image.
2021-06-27 11:36:32,196 - octolapse.script - ERROR - Error output (stderr) for 'DSLR - Snapshot Camera Script':
	ERROR: Could not get image.
2021-06-27 11:40:40,635 - octolapse.script - ERROR - An error occurred while executing 'DSLR SD - Snapshot Camera Script'
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octolapse/script.py", line 248, in execute_process
    self.proc = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/home/pi/scripts/take-snapshot-to-sd.sh'
2021-06-27 11:40:59,503 - octolapse.script - ERROR - An error occurred while executing 'DSLR SD - Snapshot Camera Script'
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octolapse/script.py", line 248, in execute_process
    self.proc = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/pi/scripts/take-snapshot-to-sd.sh'
2021-06-27 11:41:00,768 - octolapse.script - ERROR - An error occurred while executing 'DSLR SD - Snapshot Camera Script'
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octolapse/script.py", line 248, in execute_process
    self.proc = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/pi/scripts/take-snapshot-to-sd.sh'
2021-06-27 11:41:39,146 - octolapse.script - ERROR - An error occurred while executing 'DSLR SD - Snapshot Camera Script'
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octolapse/script.py", line 248, in execute_process
    self.proc = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/pi/scripts/take-snapshot-to-sd.sh'
2021-06-27 11:41:58,378 - octolapse.script - ERROR - Error output (stderr) for 'DSLR - Snapshot Camera Script':
	ERROR: Could not get image.
2021-06-27 11:42:10,716 - octolapse.script - ERROR - An error occurred while executing 'DSLR SD - Snapshot Camera Script'
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octolapse/script.py", line 248, in execute_process
    self.proc = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/pi/scripts/take-snapshot-to-sd.sh'
2021-06-27 11:44:19,921 - octolapse.script - ERROR - An error occurred while executing 'DSLR SD - Snapshot Camera Script'
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octolapse/script.py", line 248, in execute_process
    self.proc = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/pi/scripts/take-snapshot-to-sd.sh'
2021-06-27 11:33:23,703 - octolapse.__init__ - INFO - Started logging to file.
2021-06-27 11:33:23,712 - octolapse.settings - INFO - Loading existing settings file from: /home/pi/.octoprint/data/octolapse/settings.json.
2021-06-27 11:33:23,745 - octolapse.settings - INFO - Creating settings from iterable.
2021-06-27 11:33:23,800 - octolapse.settings - INFO - Settings created from iterable.
2021-06-27 11:33:23,801 - octolapse.settings - INFO - Settings file loaded.
2021-06-27 11:50:39,009 - octolapse.script - ERROR - An error occurred while executing 'DSLR SD - Snapshot Camera Script'
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octolapse/script.py", line 248, in execute_process
    self.proc = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/pi/scripts/take-snapshot-to-sd.sh'
2021-06-27 11:50:43,725 - octolapse.script - ERROR - Error output (stderr) for 'DSLR - Snapshot Camera Script':
	ERROR: Could not get image.
2021-06-27 11:52:35,955 - octolapse.script - ERROR - An error occurred while executing 'DSLR SD - Snapshot Camera Script'
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octolapse/script.py", line 248, in execute_process
    self.proc = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/pi/scripts/take-snapshot-to-sd.sh'
2021-06-27 11:52:39,513 - octolapse.script - ERROR - Error output (stderr) for 'DSLR - Snapshot Camera Script':
	ERROR: Could not get image.
2021-06-27 11:50:29,013 - octolapse.__init__ - INFO - Started logging to file.
2021-06-27 11:50:29,030 - octolapse.settings - INFO - Loading existing settings file from: /home/pi/.octoprint/data/octolapse/settings.json.
2021-06-27 11:59:19,478 - octolapse.settings - INFO - Creating settings from iterable.
2021-06-27 11:59:19,804 - octolapse.settings - INFO - Settings created from iterable.
2021-06-27 11:59:19,812 - octolapse.settings - INFO - Settings file loaded.
2021-06-27 12:19:30,744 - octolapse.__init__ - INFO - Started logging to file.
2021-06-27 12:19:30,749 - octolapse.settings - INFO - Loading existing settings file from: /home/pi/.octoprint/data/octolapse/settings.json.
2021-06-27 12:19:30,777 - octolapse.settings - INFO - Creating settings from iterable.
2021-06-27 12:19:30,832 - octolapse.settings - INFO - Settings created from iterable.
2021-06-27 12:19:30,832 - octolapse.settings - INFO - Settings file loaded.
2021-06-27 19:01:51,965 - octolapse.script - ERROR - Error output (stderr) for 'DSLR - Snapshot Camera Script':
	ERROR: Could not get image.
2021-06-27 19:02:41,994 - octolapse.script - ERROR - Error output (stderr) for 'DSLR - Snapshot Camera Script':
	ERROR: Could not get image.
2021-06-27 19:04:11,264 - octolapse.script - ERROR - An error occurred while executing 'DSLR SD - Snapshot Camera Script'
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octolapse/script.py", line 248, in execute_process
    self.proc = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/pi/scripts/take-snapshot-to-sd.sh'
2021-06-27 19:04:27,571 - octolapse.script - ERROR - An error occurred while executing 'DSLR SD - Snapshot Camera Script'
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octolapse/script.py", line 248, in execute_process
    self.proc = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/pi/scripts/take-snapshot-to-sd.sh'

```
