### ISSUE TITLE
Rendering fails after upgrade to 1.7.0

### ISSUE THREAD

**Issue by speedysk1** [FormerLurker/Octolapse#771]
After upgrading to OctoPrint 1.7.0, my time lapses are no longer rendering.  They simply remain in the queue.  Here is the log message.

2021-10-15 02:14:26,157 - octolapse.render - ERROR - Rendering Error
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octolapse/render.py", line 1565, in _render
    self._apply_pre_post_roll()
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octolapse/render.py", line 2137, in _apply_pre_post_roll
    self._temp_rendering_dir, self._render_job_info.snapshot_filename_format % 0
TypeError: not enough arguments for format string
[settings.json.txt](https://github.com/FormerLurker/Octolapse/files/7354395/settings.json.txt)
[plugin_octolapse.log](https://github.com/FormerLurker/Octolapse/files/7354396/plugin_octolapse.log)

**Comment by SMHRambo** [comment]
I have the same error

Raspberry Pi 3
Docker

Versions:
OctoPrint: 1.7.0
Release Channel: Stable
Installed: 1.7.0
Available: 1.7.0
Release Notes: https://github.com/OctoPrint/OctoPrint/releases/tag/1.7.0

Octolapse: 0.4.1
Release Channel: Stable
Installed: 0.4.1
Available: v0.4.1
Release Notes: https://github.com/FormerLurker/Octolapse/releases/tag/v0.4.1

2021-10-30 01:00:12,906 - octolapse.render - ERROR - Rendering Error
Traceback (most recent call last):
  File "/octoprint/plugins/lib/python3.8/site-packages/octoprint_octolapse/render.py", line 1565, in _render
    self._apply_pre_post_roll()
  File "/octoprint/plugins/lib/python3.8/site-packages/octoprint_octolapse/render.py", line 2137, in _apply_pre_post_roll
    self._temp_rendering_dir, self._render_job_info.snapshot_filename_format % 0
TypeError: not enough arguments for format string

**Comment by ldiegos** [comment]
hi,
I ended up donwgrading the Octoprint to 1.6.1, the previous version, and everything starts working again. But, all the renderings that fails, can't recover them, not render them any more, so i decided to delete all of them.

**Comment by speedysk1** [comment]
I think the issue is something with the file names.  Either length, spaces, special characters, something.  I did a quick test and sent a gcode file with a small name and it worked.  My "normal" naming conventions do not, but they have previously.

See below.

![image](https://user-images.githubusercontent.com/79531416/139900491-b0d4e230-3c0a-4ee1-8d0e-b0f5c16fb083.png)

**Comment by DanielGnzlzVll** [comment]
I had the same issue and I fixed it by removing white spaces and slashes from the file name.
