### ISSUE TITLE
Error in runing test for Octolapse for Cannon EOS R camera in the test of script.

### ISSUE THREAD

**Issue by forndog** [FormerLurker/Octolapse#785]
**Versions**
OctoPrint 1.7.2, Python 2.7.16, OctoPi 0.17.0

**When you ran into the problem, did you have diagnostic logging enabled?**
2021-11-14 17:03:18,619 - octolapse.settings - ERROR - An unexpected exception occurred while updating webcam settings.
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_octolapse/settings.py", line 1460, in update
    if "controls" in value:
TypeError: argument of type 'MjpgStreamer' is not iterable
2021-11-14 17:03:18,620 - octolapse.settings - ERROR - Settings._update - Failed to update settings.  Key:webcam_settings, Value:<octoprint_octolapse.settings.WebcamSettings object at 0x6bfe38d0>
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_octolapse/settings.py", line 130, in _update
    class_item.update(value)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_octolapse/settings.py", line 1484, in update
    raise e
TypeError: argument of type 'MjpgStreamer' is not iterable
2021-11-14 17:03:18,633 - octolapse.settings - ERROR - An unexpected exception occurred while updating webcam settings.
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_octolapse/settings.py", line 1460, in update
    if "controls" in value:
TypeError: argument of type 'MjpgStreamer' is not iterable
2021-11-14 17:03:18,633 - octolapse.settings - ERROR - Settings._update - Failed to update settings.  Key:webcam_settings, Value:<octoprint_octolapse.settings.WebcamSettings object at 0x75fba6f0>
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_octolapse/settings.py", line 130, in _update
    class_item.update(value)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_octolapse/settings.py", line 1484, in update
    raise e
TypeError: argument of type 'MjpgStreamer' is not iterable
2021-11-14 17:03:18,635 - octolapse.settings - INFO - Saving settings to: /home/pi/.octoprint/data/octolapse/settings.json.
2021-11-14 17:03:18,777 - octolapse.settings - INFO - Settings saved.
2021-11-14 17:03:30,441 - octolapse.script - DEBUG - Executing Canon EOS R - Snapshot Camera Script: "/home/pi/scripts/take-snapshot.sh" "0" "125" "/tmp/tmppDF2KY" "/tmp/tmppDF2KY/d8163e97-861b-4e85-960f-08c5016de7a0/31335ffd-d5c6-4832-9919-b6b4a380200e" "test_snapshot000000.jpg" "/tmp/tmppDF2KY/d8163e97-861b-4e85-960f-08c5016de7a0/31335ffd-d5c6-4832-9919-b6b4a380200e/test_snapshot000000.jpg" "Canon EOS R"
2021-11-14 17:03:36,585 - octolapse.script - DEBUG - Console output (stdout) for 'Canon EOS R - Snapshot Camera Script':Creating directory: /tmp/tmppDF2KY/d8163e97-861b-4e85-960f-08c5016de7a0/31335ffd-d5c6-4832-9919-b6b4a380200e
	Model                          Port            
	----------------------------------------------------------
	USB PTP Class Camera           usb:001,008     
	New file is in location /capt0000.jpg on the camera
	Saving file as /tmp/tmppDF2KY/d8163e97-861b-4e85-960f-08c5016de7a0/31335ffd-d5c6-4832-9919-b6b4a380200e/test_snapshot000000.jpg
	Deleting file /capt0000.jpg on the camera
	New file is in location /capt0000.jpg on the camera
	File /tmp/tmppDF2KY/d8163e97-861b-4e85-960f-08c5016de7a0/31335ffd-d5c6-4832-9919-b6b4a380200e/test_snapshot000000.jpg exists. Overwrite? [y|n] 
2021-11-14 17:03:36,586 - octolapse.script - ERROR - Error output (stderr) for 'Canon EOS R - Snapshot Camera Script':
	ERROR: Could not get image.

**Diagnostic Logging was Enabled:** YES

**What were you doing when the problem occurred**
Running test script to set up camera on octoprint 
![image](https://user-images.githubusercontent.com/94256732/141690952-75a072a1-2836-4705-8b9e-ada15d788ecb.png)
![image](https://user-images.githubusercontent.com/94256732/141690998-b7555018-ea8c-43a7-af4c-697523c7168b.png)
![image](https://user-images.githubusercontent.com/94256732/141691012-1c5f0c38-cfa5-463d-a7ba-7eb74f5ba838.png)
![image](https://user-images.githubusercontent.com/94256732/141691058-c21dd0cd-354a-40de-90b0-3a75b7998cc3.png)
![image](https://user-images.githubusercontent.com/94256732/141691125-6aa0953d-901a-471b-950e-0da07861ba84.png)

**What should have happened?**
Test should've succeeded but error occurred 

**What happened instead?**
Outlined Above

**Operating System running OctoPrint and Octolapse
Printer model & used firmware incl. version**
Printer Model:MK3S

**Comment by forndog** [comment]
So I was actually able to solve this issue myself through another thread. Make sure your camera is set to only take JPEGs and not JPEG + RAW
