### ISSUE TITLE
Octolapse not starting with Simplify v5

### ISSUE THREAD

**Issue by Eerier** [FormerLurker/Octolapse#885]
#### If this is a feature request describe it here

___REPLACE_THIS__FEATURE_REQUEST_DESCRIPTION_GOES_HERE

#### Version of Octolapse
 
Octolapse Version: 0.4.1

#### Version of OctoPrint

OctoPrint Version: 1.8.6

#### When you ran into the problem, did you have diagnostic logging enabled?

Diagnostic Logging was Enabled: yes

#### What were you doing when the problem occurred

1. uploading a gcode from Simplify v5
2. tried to start print
3. tried another gcode

#### What should have happened?
the printer should have printed and octolapse should have taken snapshots like it does with gcodes from simplify v4

#### What happened instead?
thi print aborted immediately because of the following KeyError: 'rapid_xy_speed'

#### Operating System running OctoPrint and Octolapse

OS Name: octopi
Os Version: 1.0.0

#### Printer model & used firmware incl. version

Printer Model: Ender 3v2
Printer Firmware Version: ___REPLACE_THIS__PRINTER_FIRMWARE_VERSION_GOES_HERE

#### Browser and version of browser, operating system running browser

Browser: ___REPLACE_THIS__BROWSER_VERSION_GOES_HERE
Browser OS: ___REPLACE_THIS__BROWSER_OS_GOES_HERE

#### Link to the gcode file you were printing when the problem occurred

Link to Gcode File: ___REPLACE_THIS__GCODE_FILE_LINK_GOES_HERE

#### Link to settings.json

Link to settings.json with all passwords removed: ___REPLACE_THIS__SETTINGS_JSON_LINK_GOES_HERE

#### Link to plugin_octolapse.log

Link to plugin_octolapse.log:  LINK_GOES_HERE

#### Link to octoprint.log

Link to octoprint.log:  ___REPLACE_THIS__LINK_GOES_HERE

#### Link to contents of Javascript console in the browser

Link to javascript console output: ___REPLACE_THIS__LINK_GOES_HERE

#### Screenshots and/or videos of the problem:

Screenshot/Video Links: ___REPLACE_THIS__LINKs_GO_HERE

## Please consider becoming a patron
If you like this project, [please support my work by becoming a patron,](https://www.patreon.com/bePatron?u=9588101) and consider adding a 'star' to the repository.  It takes a lot of time and effort to maintain the project and respond to issues.  The cost of test prints, software, cameras, printer parts, etc. can quickly add up, so every bit helps.

You can find various [videos and tutorials](https://www.youtube.com/channel/UCnnTLQetNw7FqfQOLJCMqoQ) by subscribing to my Youtube channel.  You can also [follow me on Twitter](https://twitter.com/FormerLurker1).

**Comment by zillion42** [comment]
[octoprint-systeminfo-20251027012216.zip](https://github.com/user-attachments/files/23154453/octoprint-systeminfo-20251027012216.zip)

same issue here, and thx for pointing me into this direction. 

/home/pi/.octoprint/logs/plugin_octolapse.log

```
2025-10-27 00:07:04,120 - octolapse.__init__ - ERROR - Unable to start the timelapse.
Traceback (most recent call last):
  File "/opt/octopi/oprint/lib/python3.11/site-packages/octoprint_octolapse/__init__.py", line 2448, in on_print_start
    timelapse_settings = self.get_timelapse_settings()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/octopi/oprint/lib/python3.11/site-packages/octoprint_octolapse/__init__.py", line 2719, in get_timelapse_settings
    success, error_type, error_list = current_printer_clone.get_gcode_settings_from_file(gcode_file_path)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/octopi/oprint/lib/python3.11/site-packages/octoprint_octolapse/settings.py", line 695, in get_gcode_settings_from_file
    new_slicer_settings.update_settings_from_gcode(new_settings, self)
  File "/opt/octopi/oprint/lib/python3.11/site-packages/octoprint_octolapse/settings.py", line 3035, in update_settings_from_gcode
    self.x_y_axis_movement_speed = _x_y_axis_movement_speed()
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/octopi/oprint/lib/python3.11/site-packages/octoprint_octolapse/settings.py", line 3029, in _x_y_axis_movement_speed
    return settings_dict["rapid_xy_speed"]
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'rapid_xy_speed'
```
