### ISSUE TITLE
Cannot install octolapse getting error about AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?

### ISSUE THREAD

**Issue by Firenyth** [FormerLurker/Octolapse#954]
#### If this is a feature request describe it here

___REPLACE_THIS__FEATURE_REQUEST_DESCRIPTION_GOES_HERE

#### Version of Octolapse
 
Octolapse Version: V0.4.5

#### Version of OctoPrint

OctoPrint Version: 1.10.2

#### When you ran into the problem, did you have diagnostic logging enabled?

Diagnostic Logging was Enabled:  NO

#### What were you doing when the problem occurred

1.  Trying to instll octoprint from repo
2.  get an error message module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?

#### What should have happened?
Octoprint should have been installed

#### What happened instead?
I get an error message module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?

#### Operating System running OctoPrint and Octolapse

OS Name: Ubuntu
Os Version:  24.04

#### Printer model & used firmware incl. version

Printer Model: ___REPLACE_THIS__PRINTER_MODEL_GOES_HERE
Printer Firmware Version: ___REPLACE_THIS__PRINTER_FIRMWARE_VERSION_GOES_HERE

#### Browser and version of browser, operating system running browser

Browser: ___REPLACE_THIS__BROWSER_VERSION_GOES_HERE
Browser OS: ___REPLACE_THIS__BROWSER_OS_GOES_HERE

#### Link to the gcode file you were printing when the problem occurred

Link to Gcode File: ___REPLACE_THIS__GCODE_FILE_LINK_GOES_HERE

#### Link to settings.json

Link to settings.json with all passwords removed: ___REPLACE_THIS__SETTINGS_JSON_LINK_GOES_HERE

#### Link to plugin_octolapse.log

Link to plugin_octolapse.log:  LINK_GOES_HERE

#### Link to octoprint.log

Link to octoprint.log:  ___REPLACE_THIS__LINK_GOES_HERE

#### Link to contents of Javascript console in the browser

Link to javascript console output: ___REPLACE_THIS__LINK_GOES_HERE

#### Screenshots and/or videos of the problem:

Screenshot/Video Links: ___REPLACE_THIS__LINKs_GO_HERE

## Please consider becoming a patron
If you like this project, [please support my work by becoming a patron,](https://www.patreon.com/bePatron?u=9588101) and consider adding a 'star' to the repository.  It takes a lot of time and effort to maintain the project and respond to issues.  The cost of test prints, software, cameras, printer parts, etc. can quickly add up, so every bit helps.

You can find various [videos and tutorials](https://www.youtube.com/channel/UCnnTLQetNw7FqfQOLJCMqoQ) by subscribing to my Youtube channel.  You can also [follow me on Twitter](https://twitter.com/FormerLurker1).

full log from octoprint
Installing plugin "Octolapse" from https://github.com/FormerLurker/Octolapse/archive/master.zip...
/home/firenyth/OctoPrint/bin/python3 -m pip --disable-pip-version-check install file:///tmp/tmpr45yv_xi/Octolapse-master.zip --no-cache-dir
Processing /tmp/tmpr45yv_xi/Octolapse-master.zip
Preparing metadata (setup.py): started
Preparing metadata (setup.py): finished with status 'error'
error: subprocess-exited-with-error

× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [15 lines of output]
/tmp/pip-req-build-zxxzdali/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
LONG_VERSION_PY['git'] = '''
Traceback (most recent call last):
File "<string>", line 2, in <module>
File "<pip-setuptools-caller>", line 34, in <module>
File "/tmp/pip-req-build-zxxzdali/setup.py", line 25, in <module>
plugin_version = NumberedVersion.clean_version(versioneer.get_versions(verbose=True)["version"])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/tmp/pip-req-build-zxxzdali/versioneer.py", line 1412, in get_versions
cfg = get_config_from_root(root)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/tmp/pip-req-build-zxxzdali/versioneer.py", line 342, in get_config_from_root
parser = configparser.SafeConfigParser()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Error!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output

**Comment by Firenyth** [comment]
Found my solution was an issue with versioneer file same as this previous bug report 
[[Bug]: Cannot install on Python 3.12] https://github.com/FormerLurker/Octolapse/issues/949

Had to rebuild the versioneer file from source https://github.com/python-versioneer/python-versioneer

then install the plugin from file with new versioneer.py file

I have attached a copy of the versioneer.py file I generated and used for anyone with similar issue.

[versioneer.zip](https://github.com/user-attachments/files/16503286/versioneer.zip)

**Comment by Firenyth** [comment]
> ## Firenyth,
> If I followed your message correctly you:
> 1> downloaded versioneer source and built it locally
> 2> downloaded Octolapse source
> 3> Located versioneer.py in the Octolapse source directory tree and replaced it with your version of versioneer.py
> 4> Successfully built Octolapse
> Are those the steps to follow?


If your trying to get it to work you can try these steps
1. Download octolapse source
2. Download the my versioneer.py 
3. Replace versioneer.py in octolapse with mine
4. Rezip octolapse and install from file on octoprint


The alternative is to generate your own versioneer.py file using versioneer I accomplished this by installing versioneer and running it from the octolapse directory after downloading it.
